// 3D Constants - ported and adapted from 2D version

// Canvas/Display - will be set to window size dynamically
export const CANVAS_WIDTH = window.innerWidth
export const CANVAS_HEIGHT = window.innerHeight

// 3D World dimensions
export const WORLD_SIZE = 800
export const WORLD_HEIGHT_LIMIT = 200  // Limit vertical movement
export const WORLD_CENTER = { x: 0, y: 0, z: 0 }

// Camera
export const CAMERA_DISTANCE = 80
export const CAMERA_HEIGHT = 30
export const CAMERA_FOV = 60
export const CAMERA_NEAR = 0.1
export const CAMERA_FAR = 2000

// Enemy
export const ENEMY_SPARK_SIZE = 10
export const ENEMY_FLOCKING_DISTANCE = 180
export const ENEMY_DOCK_ARRIVAL_THRESHOLD = 5
export const ENEMY_SPAWN_VELOCITY = 200
export const ENEMY_LINGER_BASE_TIME = 2
export const ENEMY_LINGER_RANDOM_TIME = 3
export const ENEMY_DOCK_VELOCITY = 100
export const ENEMY_FLOCKING_SEPARATION_DISTANCE = 40
export const ENEMY_FLOCKING_ALIGNMENT_DISTANCE = 100
export const ENEMY_ALIGNMENT_FACTOR = 0.5
export const ENEMY_SEPARATION_FORCE = 60
export const ENEMY_FAR_CHASE_FORCE = 40
export const ENEMY_CLOSE_CHASE_FORCE = 60
export const ENEMY_JITTER_MAGNITUDE = 120
export const ENEMY_JITTER_MIN_INTERVAL = 0.25
export const ENEMY_JITTER_RANDOM_INTERVAL = 0.5
export const ENEMY_RETREAT_VELOCITY = 100
export const ENEMY_VELOCITY_DAMPING = 0.98

export const ENEMY_PRIMARY_COLOR = [1.0, 0.0, 1.0, 1.0]
export const ENEMY_SECONDARY_COLOR = [1.0, 1.0, 0.0, 0.7]
export const ENEMY_SECONDARY_SIZE_FACTOR = 0.75

export const ENEMY_SPEED_INCREASE_PER_ROUND = 0.2
export const ENEMY_STARTING_COUNT = 3
export const ENEMY_STARTING_SPEED_MULTIPLIER = 1.5

export const ENEMY_RING_CHANGE_LINGER_BASE = 1
export const ENEMY_RING_CHANGE_LINGER_RANDOM = 2
export const ENEMY_RING_CHANGE_CHANCE = 0.30

export const RING_STARTING_SPEED_MULTIPLIER = 1.0
export const RING_RESPAWN_TIME = 1.0
export const RING_SPAWN_INITIAL_RADIUS = 0.001

export const ENEMY_EXPLOSION_PARTICLES = 20
export const ENEMY_EXPLOSION_DURATION = 0.5

export const CASTLE_DESTROYED_CHECK_DELAY = 1200
export const CASTLE_CENTER_ROTATION_SPEED = 0.8

// Castle/Cannon
export const CANNON_SPARK_SIZE = 24
export const CANNON_COOL_OFF_TIME = 1.3
export const CANNON_FIRE_WARMUP_TIME = 200
export const CANNON_SPARK_SPEED = 300
export const CANNON_PROJECTILE_BOUNDS = 1200

export const CANNON_SPARK_COLOR = [0.0, 1.0, 1.0, 1.0]
export const CANNON_COLOR = [0.5, 0.5, 0.5, 1.0]
export const CANNON_THICKNESS = 2

export const CASTLE_CENTRAL_HEX_COLOR = [1.0, 1.0, 1.0, 1.0]
export const CASTLE_CENTRAL_HEX_RADIUS = 15
export const CASTLE_CENTRAL_HEX_SIDES = 6

export const CASTLE_CORE_HIT_RADIUS = 15
export const CASTLE_INNER_RING_RADIUS = 60

export const TORPEDO_RING_HIT_DISTANCE = 8
export const TORPEDO_ENEMY_HIT_BUFFER = 2

export const RING_EXPLOSION_PARTICLES = 15
export const RING_EXPLOSION_DURATION = 0.5

export const PLAYER_RING_EXPLOSION_PARTICLES = 25
export const PLAYER_RING_EXPLOSION_DURATION = 0.8

export const CASTLE_EXPLOSION_MAX_SIZE = 180
export const CASTLE_EXPLOSION_LIFE = 1.8
export const CASTLE_EXPLOSION_SPIKES_BASE = 16
export const CASTLE_EXPLOSION_SPIKES_RANDOM = 8
export const CASTLE_EXPLOSION_INITIAL_SIZE = 5
export const CASTLE_EXPLOSION_DEBRIS_COUNT = 12

export const SHIP_EXPLOSION_MAX_SIZE = 45
export const SHIP_EXPLOSION_LIFE = 0.8
export const SHIP_EXPLOSION_SPIKES_BASE = 10
export const SHIP_EXPLOSION_SPIKES_RANDOM = 4
export const SHIP_EXPLOSION_INITIAL_SIZE = 2
export const SHIP_EXPLOSION_DEBRIS_COUNT = 6

// Player/Ship
export const PLAYER_STARTING_LIVES = 4
export const PLAYER_SPAWN_FORWARD_PUSH = 60
export const PLAYER_SPAWN_SIDEWAYS_PUSH = 40
export const PLAYER_SPAWN_DISTANCE_FROM_CENTER = 350
export const PLAYER_RESPAWN_DELAY_SECONDS = 3.0

export const PLAYER_SHIP_FORWARD_THRUST_FORCE = 300
export const PLAYER_SHIP_REVERSE_THRUST_FORCE = 400
export const PLAYER_SHIP_BRAKING_DECELERATION = 800
export const PLAYER_SHIP_STRAFE_THRUST_FORCE = 250
export const PLAYER_SHIP_THRUST_FACTOR = 4
export const PLAYER_SHIP_THRUST_DECELERATE_FACTOR = 6
export const PLAYER_SHIP_ROTATION_SPEED = 2.0

export const PLAYER_SHIP_STRAFE_THRUST_RAMP_UP_SPEED = 3
export const PLAYER_SHIP_STRAFE_THRUST_RAMP_DOWN_SPEED = 6

export const PLAYER_SHIP_BRAKING_VISUAL_THRESHOLD = 10
export const PLAYER_SHIP_REVERSE_VISUAL_THRESHOLD = 5

export const SHIP_SIZE = 12

// Weapons
export const MAX_TORPEDO_COUNT = 3
export const FORE_TORPEDO_SIZE = 8
export const AFT_TORPEDO_SIZE = 7
export const AFT_TORPEDO_SPEED_MODIFIER = 0.35
export const AFT_TORPEDO_LIFE_MODIFIER = 1.0
export const AFT_TORPEDO_COLOR = [1.0, 0.5, 0.0]
export const FORE_TORPEDO_COLOR = [1.0, 0.0, 0.1]
export const FIRE_COOLDOWN_TIME = 0.2

export const TORPEDO_JITTER_X = 110
export const TORPEDO_JITTER_Y = 110
export const TORPEDO_JITTER_TIMER = 0.1
